#!/usr/bin/env node
// scripts/prod_query.js
// Query the production server via the read-only probe API.
// Requires Replit secrets: PROD_BASE_URL and PROD_READ_TOKEN
//
// Usage:
//   node scripts/prod_query.js health
//   node scripts/prod_query.js stats
//   node scripts/prod_query.js jobs
//   node scripts/prod_query.js jobs?status=contract_signed&limit=10
//   node scripts/prod_query.js jobs/<job-id>
//   node scripts/prod_query.js payments?job_id=<job-id>
//   node scripts/prod_query.js errors

require('dotenv').config();

const https = require('https');
const http = require('http');

const BASE_URL = process.env.PROD_BASE_URL;
const TOKEN = process.env.PROD_READ_TOKEN;

if (!BASE_URL || !TOKEN) {
  console.error('\nMissing secrets. Add to Replit Settings → Secrets:');
  console.error('  PROD_BASE_URL   — e.g. https://preferredbuilders.duckdns.org');
  console.error('  PROD_READ_TOKEN — the token generated by scripts/gen_probe_token.js\n');
  process.exit(1);
}

const endpoint = process.argv[2] || 'health';
const url = `${BASE_URL.replace(/\/$/, '')}/api/probe/${endpoint}`;

console.log(`\n→ GET ${url}\n`);

function fetch(urlStr) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(urlStr);
    const lib = parsed.protocol === 'https:' ? https : http;
    const opts = {
      hostname: parsed.hostname,
      port: parsed.port || (parsed.protocol === 'https:' ? 443 : 80),
      path: parsed.pathname + parsed.search,
      method: 'GET',
      headers: { Authorization: `Bearer ${TOKEN}` },
    };
    const req = lib.request(opts, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.end();
  });
}

fetch(url)
  .then(({ status, body }) => {
    if (status !== 200) {
      console.error(`HTTP ${status}:`, body);
      process.exit(1);
    }
    try {
      const data = JSON.parse(body);
      console.log(JSON.stringify(data, null, 2));
    } catch {
      console.log(body);
    }
  })
  .catch((err) => {
    console.error('Request failed:', err.message);
    process.exit(1);
  });
